src/Entity/Hotel.php
<?php

namespace App\Entity;

use App\Repository\HotelRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=HotelRepository::class)
 */
class Hotel
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adress;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $image;

    /**
     * @ORM\Column(type="integer")
     */
    private $prix;

    /**
     * @ORM\Column(type="integer")
     */
    private $prix_enfant;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $image1;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $image2;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    public $imageModif;

    public $image1Modif;

    public $image2Modif;

    /**
     * @ORM\ManyToOne(targetEntity=Villes::class, inversedBy="hotel")
     * @ORM\JoinColumn(nullable=false)
     */
    private $ville;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getAdress(): ?string
    {
        return $this->adress;
    }

    public function setAdress(string $adress): self
    {
        $this->adress = $adress;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getPrix(): ?int
    {
        return $this->prix;
    }

    public function setPrix(int $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    public function getPrixEnfant(): ?int
    {
        return $this->prix_enfant;
    }

    public function setPrixEnfant(int $prix_enfant): self
    {
        $this->prix_enfant = $prix_enfant;

        return $this;
    }

    public function getImage1(): ?string
    {
        return $this->image1;
    }

    public function setImage1(string $image1): self
    {
        $this->image1 = $image1;

        return $this;
    }

    public function getImage2(): ?string
    {
        return $this->image2;
    }

    public function setImage2(string $image2): self
    {
        $this->image2 = $image2;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getVille(): ?Villes
    {
        return $this->ville;
    }

    public function setVille(?Villes $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

}

src/Form/HotelType.php
<?php

namespace App\Form;

use App\Entity\Hotel;
use App\Entity\Villes;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\MoneyType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

class HotelType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        if($options['ajouter'])
        {
        $builder
            ->add('name')
            ->add('description')
            ->add('adress')
            ->add('ville', EntityType::class, [
                "class"=>Villes::class,
                "choice_label"=>"name",
                "multiple"=>false,
                "attr"=>[
                    "class"=>"select2"
                ]

            ])


            ->add('prix', MoneyType::class)   
            ->add('prix_enfant', MoneyType::class)   

            ->add('image', FileType::class, [
                "required" => false
            ])
            ->add('image1', FileType::class, [
                "required" => false
            ])
            ->add('image2', FileType::class, [
                "required" => false
            ])

        ;
        }

        elseif($options['modifier'])
        {
            $builder
            ->add('name')
            ->add('description')
            ->add('adress')



            ->add('prix', MoneyType::class)   
            ->add('prix_enfant', MoneyType::class)   

            ->add('imageModif', FileType::class, [
                "required" => false
            ])
            ->add('image1Modif', FileType::class, [
                "required" => false
            ])
            ->add('image2Modif', FileType::class, [
                "required" => false
            ]) 
        ;

        }
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Hotel::class,
            'ajouter' => false,
            'modifier' => false
        ]);
    }
}

src/Controller/HotelController.php
<?php

namespace App\Controller;

use App\Entity\Hotel;
use App\Form\HotelType;
use App\Repository\HotelRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class HotelController extends AbstractController
{
    /**
     * @Route("/hotel_afficher", name="hotel_afficher")
     */
    public function produit_afficher(HotelRepository $repoHotel)
    {
        $hotelsArray = $repoHotel->findAll();
        //dd($hotelsArray);

        return $this->render('hotel/hotel_afficher.html.twig', [
            "hotels" => $hotelsArray
        ]);
    }

     /**
     * @Route("/hotel_ajouter", name="hotel_ajouter")
     */
    public function addHotel(Request $request, EntityManagerInterface $manager)
    {

        $hotel = new Hotel;

        $form = $this->createForm(HotelType::class, $hotel, [
            "ajouter"=> true
        ]);

        $form->handleRequest($request); 

        if ($form->isSubmitted() && $form->isValid()) {

             $imageFile = $form->get('image')->getData();
            // $imageFile est soit un objet soit null
            //dd($imageFile);


            if ($imageFile) // si $imageFile n'est pas vide/null (une image a été upload/chargée)
            {
                // Traitement de l'image
                // 3 étapes

                // 1e étape : renommer le nom de l'image

                $nomImage = date("YmdHis") . "-" . uniqid() . "-" . $imageFile->getClientOriginalName();
                //dd($nomImage);


                // 2e étape : Envoyer l'image dans le dossier public / images / imagesUpload

                // move() permet de déplacer le fichier
                // 2 arguments :
                // 1e : emplacement : getParameter()        // où déplacer l'image ???
                // 2e : le nom du fichier qu'on déplace      // sous quel nom ???

                $imageFile->move(
                    $this->getParameter("image_hotel"),
                    $nomImage
                );

                /*
                    la méthode getParameter() renvoie sur le fichier config/services.yaml aux paramètres (ligne 6)
                    les paramètres définissent un emplacement 
                    1 argument : le nom du paramètre
                */


                // 3e étape : envoyer le nom de l'image en bdd

                $hotel->setImage($nomImage); 


            }// fermeture de la condition $imageFile
            


            //$hotel->setDateAt(new \DateTimeImmutable('now'));

            //dump($produit);
            //

            $manager->persist($hotel); // on défini ce qu'on envoie
            $manager->flush(); // envoie de l'objet $produit en BDD dans la table Produit

            //dd($produit);


            // notification 
            // methode addFlash() provenant de AbstractController qui permet de véhiculer sur le twig un message
            // 2 arguments :
            // 1e : le nom du flash
            // 2e : le message

            $this->addFlash('success', "L'hotel N° " . $hotel->getId() . " a bien été ajouté");


            // Redirection
            // methode redirectToRoute() de AbstractController
            // 2 arguments :
            // 1e obligatoire : name de la route
            // 2e facultatif : tableau


            return $this->redirectToRoute("hotel_afficher");
        }


        return $this->render('hotel/hotel_ajouter.html.twig', [
            "formHotel" => $form->createView()
        ]);
    }


    /**
     * @Route("/hotel_supprimer/{id}", name="hotel_supprimer")
     */
    public function hotel_supprimer(Hotel $hotel, EntityManagerInterface $manager)
    {
        // si $hotel a une image alors il faut également la supprimer
        if ($hotel->getImage()) // si l'image n'est pas null
        {
            //  unlink($this->getParameter("image_produit") . "/" . $produit->getImage());
            //unlink() permet de supprimer un fichier
            // 1e argument : le chemin jusqu'au fichier
        }

        $nom = $hotel->getName();
        // suppression
        $manager->remove($hotel);
        $manager->flush();

        // notification
        $this->addFlash("success", "L'hotel $nom a bien été supprimé");


        // redirection
        return $this->redirectToRoute("hotel_afficher");

    }

    /**
     * @Route("hotel_modifier/{id}", name="hotel_modifier")
     */
    public function hotel_modifier(Hotel $hotel, Request $request, EntityManagerInterface $manager)
    {
        $form = $this->createForm(HotelType::class, $hotel, [
            "modifier" => true
        ]);

        $form->handleRequest($request); // traitement du formulaire

        // si le formulaire a été soumis (clic sur le bouton "Ajouter" : type="submit")
        // et si le formulaire est valide (contraintes : il respecte toutes les conditions : ex: prix, titre non vides)
        if ($form->isSubmitted() && $form->isValid()) {
            //dump($produit);

            //dd($produit->getTitre());

            $imageModif = $form->get('imageModif')->getData();
            // $imageFile est soit un objet soit null
            //dd($imageModif);
            $image1Modif = $form->get('image1Modif')->getData();
            // $imageFile est soit un objet soit null
            //dd($imageFile);
            $image2Modif = $form->get('image2Modif')->getData();
            // $imageFile est soit un objet soit null
            //dd($imageFile);


            if ($imageModif) // si $imageFile n'est pas vide/null (une image a été upload/chargée)
            {
                // Traitement de l'image
                // 3 étapes

                // 1e étape : renommer le nom de l'image

                $nomImage = date("YmdHis") . "-" . uniqid() . "-" . $imageModif->getClientOriginalName();
                //dd($nomImage);


                // 2e étape : Envoyer l'image dans le dossier public / images / imagesUpload

                // move() permet de déplacer le fichier
                // 2 arguments :
                // 1e : emplacement : getParameter()        // où déplacer l'image ???
                // 2e : le nom du fichier qu'on déplace      // sous quel nom ???

                $imageModif->move(
                    $this->getParameter("image_hotel"),
                    $nomImage
                );

                /*
                    la méthode getParameter() renvoie sur le fichier config/services.yaml aux paramètres (ligne 6)
                    les paramètres définissent un emplacement 
                    1 argument : le nom du paramètre
                */


                // 3e étape : envoyer le nom de l'image en bdd

                $hotel->setImage($nomImage);


            }// fermeture de la condition $imageFile

            
            
            if ($image1Modif) // si $imageFile n'est pas vide/null (une image a été upload/chargée)
            {
                // Traitement de l'image
                // 3 étapes

                // 1e étape : renommer le nom de l'image

                $nomImage1 = date("YmdHis") . "-" . uniqid() . "-" . $image1Modif->getClientOriginalName();
                //dd($nomImage);


                // 2e étape : Envoyer l'image dans le dossier public / images / imagesUpload

                // move() permet de déplacer le fichier
                // 2 arguments :
                // 1e : emplacement : getParameter()        // où déplacer l'image ???
                // 2e : le nom du fichier qu'on déplace      // sous quel nom ???

                $image1Modif->move(
                    $this->getParameter("image_hotel1"),
                    $nomImage1
                );

                /*
                    la méthode getParameter() renvoie sur le fichier config/services.yaml aux paramètres (ligne 6)
                    les paramètres définissent un emplacement 
                    1 argument : le nom du paramètre
                */


                // 3e étape : envoyer le nom de l'image en bdd

                $hotel->setImage1($nomImage1);


            }// fermeture de la condition $imageFile

            if ($image2Modif) // si $imageFile n'est pas vide/null (une image a été upload/chargée)
            {
                // Traitement de l'image
                // 3 étapes

                // 1e étape : renommer le nom de l'image

                $nomImage2 = date("YmdHis") . "-" . uniqid() . "-" . $image2Modif->getClientOriginalName();
                //dd($nomImage);


                // 2e étape : Envoyer l'image dans le dossier public / images / imagesUpload

                // move() permet de déplacer le fichier
                // 2 arguments :
                // 1e : emplacement : getParameter()        // où déplacer l'image ???
                // 2e : le nom du fichier qu'on déplace      // sous quel nom ???

                $image2Modif->move(
                    $this->getParameter("image_hotel2"),
                    $nomImage2
                );

                /*
                    la méthode getParameter() renvoie sur le fichier config/services.yaml aux paramètres (ligne 6)
                    les paramètres définissent un emplacement 
                    1 argument : le nom du paramètre
                */


                // 3e étape : envoyer le nom de l'image en bdd

                $hotel->setImage2($nomImage2);


            }// fermeture de la condition $imageFile


            //dump($produit);
            //

            $manager->persist($hotel); // on défini ce qu'on envoie
            $manager->flush(); // envoie de l'objet $produit en BDD dans la table Produit

            //dd($produit);


            // notification 
            // methode addFlash() provenant de AbstractController qui permet de véhiculer sur le twig un message

templates/hotel/hotel_afficher.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ parent() }} | Back Office | Gestion des hotels{% endblock %}




{% block h1 %}Gestion des hotels{% endblock %}

{% block body %}

    {# Notification #}
    {# app est une variable d'environnement #}
    {% for notification in app.flashes('success') %}
        <div class="alert alert-success col-md-6 mx-auto text-center">{{ notification }}</div>
    {% endfor %}


    <div class="row justify-content-end">
        <a class="btn btn-primary col-md-2 m-2" href="{{ path('hotel_ajouter') }}">Ajouter un hotel</a>
    </div>

    {% if hotels is not empty %} 

       <table class="table table-hover table-striped text-center mt-3">

            <thead class="bg-dark text-white">
                <tr>
                    <th>ID</th>
                    <th>Nom</th>
                    <th>Prix Adulte</th>
                    <th>Prix Enfants</th>
                    <th>Adresse</th>
                    <th>Ville</th>
                    <th>Pays</th>
                    <th>Image</th>
                    <th>Modifier</th>
                    <th>Supprimer</th>
                </tr>
            </thead>

            <tbody>


                {% for hotel in hotels %}
                {# produits c'est le tableau qu'on récupère du controller 
                Il contient tous les produits (objets) de la table Produit 
                On va boucler chaque objet
                pour appeler une propriété de l'objet la syntaxe est 
                objet.propriété
                #}
                    
                    <tr class="align-middle">

                        <td>{{ hotel.id }}</td>

                        <td>{{ hotel.name }}</td>

                        <td>{{ hotel.prix }}</td>

                        <td>{{ hotel.prixEnfant }}</td>

                        <td>{{ hotel.adress }}</td>

                        <td>{{ hotel.ville.name }}</td>

                        <td>{{ hotel.ville.pays.name }}</td>

                        <td>
                            {% if hotel.image is not empty %}
                                {# pour afficher une image upload, on doit définir dans l'attribut src="" son emplacement et le nom du fichier
                                    On sait qu'il se trouve dans le dossier public ===> fonction asset()
                                    à l'intérieur, dans le dossier images
                                    puis dans le dossier imagesUpload
                                    jusqu'ici c'est une chaîne de caractères (quote)
                                    le nom du fichier, on le retrouve dans notre objet produit (id/titre/prix/image)
                                    ==> produit.image (20210723......bague.jpg)
                                    la concaténation en twig est le tilde ~ (mac : alt n  // windows : alt gr 2)
                                 #}

                                <img src="{{ asset('images/imagesUpload/' ~ hotel.image ) }}" style="width:80px" alt="">  

                                {#<img src="{{ asset("images/imagesUpload/#{produit.image}" ) }}" style="width:80px" alt="">#}
                            {% else %}
                                <img src="{{ asset('images/imageDefault.jpg') }}" style="width:80px" alt=""> 
                            {% endif %}

                        </td>

                        <td>
                            <a href="{{ path("hotel_modifier", {"id":hotel.id} ) }}">
                                <img src="{{ asset('images/update.png') }}" alt=""> 
                            </a>
                        </td>

                        <td>
                            <a href="{{ path("hotel_supprimer", {"id":hotel.id} ) }}" onclick="return confirm('Confirmez-vous la suppression de l\'hotel?')">
                                <img src="{{ asset('images/delete.png') }}" alt="">
                            </a>
                        </td>


                    
                    
                    
                    
                    </tr>


                {% endfor %}
            
            
            </tbody>
       
       
       </table>


    {% else %}{# si produits est vide #}

        <h4 class="text-center text-danger fst-italic mt-3">Il n'y a pas de produits pour le moment</h4>

    {% endif %}


       
{% endblock %}

templates/hotel/hotel_ajouter.html.twig
{% extends 'base.html.twig' %}

{% block title %}
 {{ parent() }}Hotel Ajouter
{% endblock %}

{% block body %}

    <div class="col-md-6 mx-auto">
        {{ form_start(formHotel) }} 

                        

            {{ form_row(formHotel.name, {
                "attr" : {
                    "placeholder" : "saisir le titre"
                    } 
                }) 
            }}

            {{ form_row(formHotel.description, {
                "attr" : {
                    "placeholder" : "saisir la description"
                    } 
                }) 
            }}

            {{ form_row(formHotel.adress, {
                "attr" : {
                    "placeholder" : "saisir l'adresse"
                    } 
                }) 
            }}

            {{ form_row(formHotel.ville, {
                "attr" : {
                    "placeholder" : "saisir l'adresse"
                    } 
                }) 
            }}


            
            <div class="row">

                {{ form_label(formHotel.prix) }}

                <div class="col-md-6">

                    {{ form_widget(formHotel.prix) }}

                </div>

                <div class="col-md-6">
                    {{ form_errors(formHotel.prix) }}
                </div>




                {{ form_label(formHotel.prix_enfant) }}

                <div class="col-md-6">

                    {{ form_widget(formHotel.prix_enfant) }}

                </div>

                <div class="col-md-6">
                    {{ form_errors(formHotel.prix_enfant) }}
                </div>


            </div>

            {{ form_row(formHotel.image, {
                "attr" : {
                    "onChange" : "loadFile(event)"
                    } 
                }) 
            }}

            <div class="row justify-content-center">
            
                <img id="image" style='width:300px'>
            
            </div>

            {{ form_row(formHotel.image1, {
                "attr" : {
                    "onChange" : "loadFile1(event)"
                    } 
                }) 
            }}

            <div class="row justify-content-center">
            
                <img id="image1" style='width:300px'>
            
            </div>

            {{ form_row(formHotel.image2, {
                "attr" : {
                    "onChange" : "loadFile2(event)"
                    } 
                }) 
            }}

            <div class="row justify-content-center">
            
                <img id="image2" style='width:300px'>
            
            </div>

            



            <input type="submit" value="Ajouter" class="btn btn-dark text-white col-md-12 mt-3">

        {{ form_end(formHotel) }}
    </div>

        <script>
    let loadFile = function(event)
{
    let image = document.getElementById('image');

    image.src = URL.createObjectURL(event.target.files[0]);
}

let loadFile1 = function(event)
{
    let image1 = document.getElementById('image1');

    image1.src = URL.createObjectURL(event.target.files[0]);
}

let loadFile2 = function(event)
{
    let image2 = document.getElementById('image2');

    image2.src = URL.createObjectURL(event.target.files[0]);
}
    
    </script>   
    

{% endblock %}

templates/hotel/hotel_modifier.html.twig
{% extends 'base.html.twig' %}

{% block title %}
 {{ parent() }}Hotel Modifier
{% endblock %}

{% block body %}

    <div class="col-md-6 mx-auto">
        {{ form_start(formHotel) }} 

                        

            {{ form_row(formHotel.name, {
                "attr" : {
                    "placeholder" : "saisir le titre"
                    } 
                }) 
            }}

            {{ form_row(formHotel.description, {
                "attr" : {
                    "placeholder" : "saisir la description"
                    } 
                }) 
            }}

            {{ form_row(formHotel.adress, {
                "attr" : {
                    "placeholder" : "saisir l'adresse"
                    } 
                }) 
            }}

            {{ form_row(formHotel.city, {
                "attr" : {
                    "placeholder" : "saisir la ville"
                    } 
                }) 
            }}

            {{ form_row(formHotel.country, {
                "attr" : {
                    "placeholder" : "saisir le pays"
                    } 
                }) 
            }}
            
            <div class="row">

                {{ form_label(formHotel.prix) }}

                <div class="col-md-6">

                    {{ form_widget(formHotel.prix) }}

                </div>

                <div class="col-md-6">
                    {{ form_errors(formHotel.prix) }}
                </div>




                {{ form_label(formHotel.prix_enfant) }}

                <div class="col-md-6">

                    {{ form_widget(formHotel.prix_enfant) }}

                </div>

                <div class="col-md-6">
                    {{ form_errors(formHotel.prix_enfant) }}
                </div>


            </div>

            {{ form_row(formHotel.imageModif, {
                "attr" : {
                    "onChange" : "loadFile(event)"
                    } 
                }) 
            }}

            <div class="row justify-content-center">
            
                <img id="image" style='width:300px'>
            
            </div>

            {{ form_row(formHotel.image1Modif, {
                "attr" : {
                    "onChange" : "loadFile1(event)"
                    } 
                }) 
            }}

            <div class="row justify-content-center">
            
                <img id="image1" style='width:300px'>
            
            </div>

            {{ form_row(formHotel.image2Modif, {
                "attr" : {
                    "onChange" : "loadFile2(event)"
                    } 
                }) 
            }}

            <div class="row justify-content-center">
            
                <img id="image2" style='width:300px'>
            
            </div>

            



            <input type="submit" value="Ajouter" class="btn btn-dark text-white col-md-12 mt-3">

        {{ form_end(formHotel) }}
    </div>


    <script>
    let loadFile = function(event)
{
    let image = document.getElementById('image');

    image.src = URL.createObjectURL(event.target.files[0]);
}

let loadFile1 = function(event)
{
    let image1 = document.getElementById('image1');

    image1.src = URL.createObjectURL(event.target.files[0]);
}

let loadFile2 = function(event)
{
    let image2 = document.getElementById('image2');

    image2.src = URL.createObjectURL(event.target.files[0]);
}
    
    </script>
    

{% endblock %}